services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_INTERFACE: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_PLAINTEXT_PORT: 9092
      KAFKA_LISTENER_NAME_INSIDE_PORT: 9093
      KAFKA_LISTENER_NAME_OUTSIDE_PORT: 9092
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    environment:
      KAFKA_BROKER_CONNECT: "kafka:9093"
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    networks:
      - kafka-net

  classification_service:
    build:
      context: ./classification_service
      dockerfile: Dockerfile
    container_name: classification_service
    depends_on:
      - kafka
      - mlflow
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - kafka-net

  image_filter_service:
    build:
      context: ./image_filter_service
      dockerfile: Dockerfile
    container_name: image_filter_service
    depends_on:
      - kafka
      - classification_service
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    networks:
      - kafka-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow-data:/mlflow
    networks:
      - kafka-net

  layout_detection_service:
    build:
      context: ./layout_detection_service
      dockerfile: Dockerfile
    container_name: layout_detection_service
    depends_on:
      - kafka
      - image_filter_service
      - mlflow
    ports:
      - "8002:8002"  
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge