version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=20809890
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak?sslmode=disable
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=20809890
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./mon-theme-keycloak/theme:/opt/keycloak/themes
    ports:
      - "8085:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=20809890
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka-net

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    environment:
      KAFKA_BROKER_CONNECT: kafka:9093
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    networks:
      - kafka-net

  # classification_service:
  #   image: myproject/classification_service:latest
  #   build:
  #     context: ./classification_service
  #     dockerfile: Dockerfile
  #   container_name: classification_service
  #   depends_on:
  #     - kafka
  #     - mlflow
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9093
  #     MLFLOW_TRACKING_URI: http://mlflow:5000
  #   networks:
  #     - kafka-net

  # image_filter_service:
  #   image: myproject/image_filter_service:latest
  #   build:
  #     context: ./image_filter_service
  #     dockerfile: Dockerfile
  #   container_name: image_filter_service
  #   depends_on:
  #     - kafka
  #     - classification_service
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9093
  #   networks:
  #     - kafka-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow-data:/mlflow
    networks:
      - kafka-net

  # layout_detection_service:
  #   image: myproject/layout_detection_service:latest
  #   build:
  #     context: ./layout_detection_service
  #     dockerfile: Dockerfile
  #   container_name: layout_detection_service
  #   depends_on:
  #     - kafka
  #     - image_filter_service
  #     - mlflow
  #   ports:
  #     - "8002:8002"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9093
  #     MLFLOW_TRACKING_URI: http://mlflow:5000
  #   networks:
  #     - kafka-net

  # extraction_service:
  #   image: myproject/extraction_service:latest
  #   build:
  #     context: ./extraction_service
  #     dockerfile: Dockerfile
  #   container_name: extraction_service
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     layout_detection_service:
  #       condition: service_started
  #   ports:
  #     - "8003:8003"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9093
  #   networks:
  #     - kafka-net


  # structuring_service:
  #   image: myproject/structuring_service:latest
  #   build:
  #     context: ./structuring_service
  #     dockerfile: Dockerfile
  #   container_name: structuring_service
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     extraction_service:
  #       condition: service_started
  #   ports:
  #     - "8004:8004"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9093
  #   networks:
  #     - kafka-net


networks:
  app-network:
    driver: bridge
  kafka-net:
    driver: bridge